FROM mirror.gcr.io/library/alpine@sha256:28bd5fe8b56d1bd048e5babf5b10710ebe0bae67db86916198a6eec434943f8b AS base
RUN dd if=/dev/zero of=/payload bs=1M count=64

FROM base AS branch-a
RUN printf a >/a

FROM base AS branch-b
RUN printf b >/b

FROM base AS branch-c
RUN printf c >/c

FROM base AS branch-d
RUN printf d >/d

FROM scratch
COPY --from=branch-a /a /a
COPY --from=branch-b /b /b
COPY --from=branch-c /c /c
COPY --from=branch-d /d /d
