#!/usr/bin/env python3
"""Engine-free ownership/lifecycle regression tests. No VM commands or network."""
from __future__ import annotations

import importlib.util
import io
import json
import os
from pathlib import Path
import shutil
import socket
import stat
import subprocess
import sys
import tempfile
from types import SimpleNamespace
from typing import Callable
import unittest
from unittest.mock import patch

MODULE = Path(__file__).resolve().parents[1] / "volume_reference.py"
spec = importlib.util.spec_from_file_location("volume_reference", MODULE)
assert spec is not None and spec.loader is not None
ref = importlib.util.module_from_spec(spec)
spec.loader.exec_module(ref)


# Exact Lima 2.2.0-generated default (not a network authorization).
DEFAULT_NETWORKS = b'''# Path to socket_vmnet executable. Because socket_vmnet is invoked via sudo it should be
# installed where only root can modify/replace it. This means also none of the
# parent directories can be writable by the user.
#
# The varRun directory also must not be writable by the user because it will
# include the socket_vmnet pid file. Those will be terminated via sudo, so replacing
# the pid file would allow killing of arbitrary privileged processes. varRun
# however MUST be writable by the daemon user.
#
# None of the paths segments may be symlinks, why it has to be /private/var
# instead of /var etc.
paths:
# socketVMNet requires Lima >= 0.12 .
  socketVMNet: "/opt/socket_vmnet/bin/socket_vmnet"
  varRun: /private/var/run/lima
  sudoers: /private/etc/sudoers.d/lima

# The group that is allowed to run socket_vmnet via sudo and to access the
# socket_vmnet socket (macOS only; ignored on other platforms). Non-admin users
# must set this to a group they belong to (e.g. "staff").
group: admin

networks:
  user-v2:
    mode: user-v2
    gateway: 192.168.104.1
    netmask: 255.255.255.0
  shared:
    mode: shared
    gateway: 192.168.105.1
    dhcpEnd: 192.168.105.254
    netmask: 255.255.255.0
  bridged:
    mode: bridged
    interface: en0
    # bridged mode doesn't have a gateway; dhcp is managed by outside network
  host:
    mode: host
    gateway: 192.168.106.1
    dhcpEnd: 192.168.106.254
    netmask: 255.255.255.0
'''


class FakeSubprocess:
    def __init__(self):
        self.calls = []
        self.sockets = []
        self.fail: str | None = None
        self.daemon_id = "reference-daemon-unique-id"
        self.engine_version = "29.2.1"
        self.lima_version = ref.LIMA_VERSION
        self.before: Callable | None = None
        self.vm_status = "Stopped"
        self.list_output: str | None = None
        self.stop_keeps_running = False
        self.retain_socket = False

    def __call__(self, argv, **kwargs):
        self.calls.append((argv, kwargs))
        root = Path(kwargs["cwd"])
        state = json.loads((root / "state.json").read_text())
        vm = root / "lima" / state["name"]
        operation = argv[1]
        if self.before:
            self.before(operation, root, vm)
        if operation == "--version":
            output = "limactl version " + self.lima_version + "\n"
        elif operation == "create":
            vm.mkdir(mode=0o700)
            # Lima is allowed to serialize JSON input to YAML; the actual stored
            # config is separately pinned after successful create, before start.
            (vm / "lima.yaml").write_text("# generated by fake Lima\n" + (root / "config.yaml").read_text())
            config = root / "lima" / "_config"
            config.mkdir(mode=0o700)
            (config / "user").write_text("private-key-fixture")
            (config / "user.pub").write_text("public-key-fixture")
            output = ""
        elif operation == "start":
            networks = root / "lima" / "_config" / "networks.yaml"
            if not networks.exists():
                networks.write_bytes(DEFAULT_NETWORKS)
            (vm / "sock").mkdir(mode=0o700, exist_ok=True)
            (vm / "sock" / "docker.sock").unlink(missing_ok=True)
            connection = socket.socket(socket.AF_UNIX)
            connection.bind(str(vm / "sock" / "docker.sock"))
            self.sockets.append(connection)
            self.vm_status = "Running"
            output = ""
        elif operation == "list":
            assert argv == [state["limactl"], "list", state["name"], "--json"]
            output = self.list_output if self.list_output is not None else json.dumps({
                "name": state["name"], "dir": str(vm), "vmType": "vz", "arch": "aarch64", "status": self.vm_status}) + "\n"
        elif operation == "--config":
            assert argv[3:7] == ["--host", state["endpoint"], "info", "--format"]
            output = json.dumps({"ID": self.daemon_id, "ServerVersion": self.engine_version,
                                 "OSType": "linux", "Architecture": "aarch64", "SecurityOptions": []})
        elif operation == "stop":
            assert argv == [state["limactl"], "stop", "--force", state["name"]]
            if not self.retain_socket:
                (vm / "sock" / "docker.sock").unlink()
            if not self.stop_keeps_running:
                self.vm_status = "Stopped"
            output = ""
        elif operation == "delete":
            assert argv == [state["limactl"], "delete", "--force", state["name"]]
            shutil.rmtree(vm)
            output = ""
        else:
            raise AssertionError("unexpected subprocess: " + repr(argv))
        kwargs["stdout"].write(output.encode())
        kwargs["stdout"].flush()
        if operation == self.fail:
            raise subprocess.TimeoutExpired(argv, kwargs["timeout"])
        return SimpleNamespace(returncode=0)

    def close(self):
        for connection in self.sockets:
            connection.close()


class ReferenceTests(unittest.TestCase):
    def setUp(self):
        self.temp = tempfile.TemporaryDirectory(prefix="vr-", dir="/tmp")
        self.base = Path(self.temp.name).resolve()
        self.root = self.base / "run"
        self.image = self.base / "image.raw"
        self.image.write_bytes(b"pinned preinstalled cloud image fixture")
        # Keep fake inputs in trusted ancestry even when the checkout volume is
        # shared/writable. This does NOT qualify that checkout for real provisioning.
        fixture = self.base / "fixture-source.txt"
        fixture.write_bytes(ref.FIXTURE_SOURCE.read_bytes())
        self.enterContext(patch.object(ref, "FIXTURE_SOURCE", fixture))
        for name in ("limactl", "docker"):
            path = self.base / name
            path.write_text("#!/bin/sh\nexit 97\n")
            path.chmod(0o700)
        self.fake = FakeSubprocess()
        self.addCleanup(self.temp.cleanup)
        self.addCleanup(self.fake.close)
        for name, value in (("system", "Darwin"), ("machine", "arm64"), ("mac_ver", ("26.0", (), ""))):
            self.enterContext(patch.object(ref.platform, name, return_value=value))
        self.enterContext(patch.object(ref.os, "statvfs", return_value=SimpleNamespace(f_bavail=1000 * 1024**3, f_frsize=1)))
        self.enterContext(patch.dict(os.environ, {"DOCKER_CONTEXT": "foreign", "DOCKER_HOST": "unix:///foreign.sock",
                          "LIMA_HOME": str(self.base / "foreign-lima"), "COLIMA_HOME": str(self.base / "foreign-colima"),
                          "SSH_AUTH_SOCK": "/foreign-agent.sock", "HTTP_PROXY": "http://foreign.invalid"}))

    def args(self, *extra):
        return ref.parser().parse_args(["provision", "--allow-disposable-vm", "--root", str(self.root),
            "--image", str(self.image), "--image-sha256", ref.digest(self.image),
            "--engine-version", "29.2.1", "--limactl", str(self.base / "limactl"),
            "--docker", str(self.base / "docker"), *extra])

    def provision(self, *extra):
        return ref.provision(self.args(*extra), self.fake)

    def receipt(self):
        return json.loads((self.root / "state.json").read_text())

    def open(self):
        return ref.Reference(self.root, self.fake)

    def assert_guarded(self, mutation):
        state = self.receipt()
        vm = self.root / "lima" / state["name"]
        mutation(state, vm)
        count = len(self.fake.calls)
        with self.assertRaises((ref.Refusal, OSError)):
            with self.open() as run:
                run.destructive("destroy", state["run_id"])
        self.assertEqual(len(self.fake.calls), count)

    def test_provision_crash_exact_teardown_and_artifacts(self):
        status = self.provision()
        self.assertEqual(status["phase"], "ready")
        self.assertEqual(status["daemon_id"], self.fake.daemon_id)
        state = self.receipt()
        self.assertEqual(state["records"]["."]["ino"], self.root.stat().st_ino)
        self.assertEqual(state["records"]["config.yaml"]["sha256"], ref.digest(self.root / "config.yaml"))
        vm = self.root / "lima" / status["name"]
        self.assertIn("sha256", state["records"][str((vm / "lima.yaml").relative_to(self.root))])
        with self.open() as run:
            self.assertEqual(run.destructive("crash", status["run_id"])["phase"], "crashed")
        with self.open() as run:
            self.assertEqual(run.destructive("destroy", status["run_id"])["phase"], "destroyed")
        count = len(self.fake.calls)
        with self.open() as run:
            self.assertEqual(run.destructive("destroy", status["run_id"])["phase"], "destroyed")
        self.assertEqual(len(self.fake.calls), count)
        self.assertFalse(vm.exists())
        self.assertTrue((self.root / "artifacts").is_dir())
        self.assertTrue((self.root / "config.yaml").is_file())
        self.assertTrue((self.root / "state.json").is_file())
        for argv, kw in self.fake.calls:
            self.assertIsInstance(argv, list)
            self.assertLessEqual(kw["timeout"], 900)
            self.assertGreater(kw["timeout"], 0)
            self.assertEqual(kw["env"]["LIMA_HOME"], str(self.root / "lima"))
            self.assertEqual(kw["env"]["HOME"], str(self.root / "host-home"))
            for name in ("DOCKER_CONTEXT", "DOCKER_HOST", "SSH_AUTH_SOCK", "HTTP_PROXY"):
                self.assertNotIn(name, kw["env"])
            self.assertNotIn("shell", kw)
            self.assertEqual(kw["stdin"], subprocess.DEVNULL)

    def test_no_templates_installs_home_mounts_or_agent(self):
        self.provision()
        config = json.loads((self.root / "config.yaml").read_text())
        self.assertNotIn("base", config)
        self.assertEqual(config["mounts"], [])
        self.assertEqual(config["networks"], [])
        self.assertEqual(config["containerd"], {"system": False, "user": False})
        self.assertFalse(config["ssh"]["forwardAgent"])
        self.assertFalse(config["ssh"]["loadDotSSHPubKeys"])
        self.assertFalse(config["upgradePackages"])
        self.assertEqual(config["portForwards"][-1],
                         {"guestPortRange": [1, 65535], "proto": "any", "ignore": True})
        self.assertTrue(config["provision"][0]["skipDefaultDependencyResolution"])
        self.assertIn("SocketUser={{.User}}", config["provision"][1]["script"])
        self.assertEqual(config["portForwards"][0]["hostSocket"], "{{.Dir}}/sock/docker.sock")
        self.assertEqual(config["images"], [{"location": str(self.image), "arch": "aarch64",
                                           "digest": "sha256:" + ref.digest(self.image)}])
        text = json.dumps(config)
        for forbidden in ("get.docker.com", "curl", "apt-get", "pgrep", "latest", "template:"):
            self.assertNotIn(forbidden, text)

    def test_owned_fixture_is_only_explicit_mount(self):
        self.provision("--owned-fixture")
        config = json.loads((self.root / "config.yaml").read_text())
        self.assertEqual(config["mounts"], [{"location": str(self.root / "fixture"),
                         "mountPoint": "/mnt/volume-reference", "writable": True}])
        self.assertEqual((self.root / "fixture" / "reference.txt").read_bytes(), ref.FIXTURE_SOURCE.read_bytes())
        self.assertEqual(self.receipt()["fixture_seed_sha256"], ref.digest(ref.FIXTURE_SOURCE))
        self.assert_guarded(lambda s, vm: (self.root / "fixture").rename(self.root / "moved-fixture"))

    def test_same_path_fixture_requires_explicit_owned_fresh_fixture(self):
        with self.assertRaisesRegex(ref.Refusal, "requires --owned-fixture"):
            self.provision("--same-path-fixture")
        self.assertFalse(self.root.exists())
        self.assertEqual(self.fake.calls, [])
        self.provision("--owned-fixture", "--same-path-fixture")
        config = json.loads((self.root / "config.yaml").read_text())
        self.assertEqual(config["mounts"], [{"location": str(self.root / "fixture"),
                         "mountPoint": str(self.root / "fixture"), "writable": True}])
        self.assertTrue(self.receipt()["same_path_fixture"])
        before = (self.root / "fixture" / "reference.txt").read_bytes()
        count = len(self.fake.calls)
        with self.assertRaisesRegex(ref.Refusal, "existing run root refused"):
            self.provision("--owned-fixture", "--same-path-fixture")
        self.assertEqual(len(self.fake.calls), count)
        self.assertEqual((self.root / "fixture" / "reference.txt").read_bytes(), before)
        self.assert_guarded(lambda s, vm: (self.root / "fixture").rename(self.root / "old-fixture"))

    def test_lima_template_paths_cannot_redirect_owned_fixture_or_image(self):
        for token in ("{{.User}}", "{{.Home}}", "literal}}"):
            for flags in (("--owned-fixture",), ("--owned-fixture", "--same-path-fixture")):
                root = self.base / token
                with self.subTest(token=token, flags=flags):
                    with self.assertRaisesRegex(ref.Refusal, "template delimiters"):
                        self.provision("--root", str(root), *flags)
                    self.assertFalse(root.exists())
            image = self.base / (token + ".raw")
            image.write_bytes(self.image.read_bytes())
            with self.assertRaisesRegex(ref.Refusal, "template delimiters"):
                self.provision("--image", str(image))
        self.assertFalse(self.root.exists())
        self.assertEqual(self.fake.calls, [])

    def test_default_networks_exact_pin_and_tamper(self):
        self.assertEqual(ref.hashlib.sha256(DEFAULT_NETWORKS).hexdigest(), ref.NETWORKS_SHA)
        self.provision()
        path = self.root / "lima" / "_config" / "networks.yaml"
        self.assertEqual(self.receipt()["globals"]["lima/_config/networks.yaml"]["sha256"], ref.NETWORKS_SHA)
        self.assert_guarded(lambda s, vm: path.write_bytes(DEFAULT_NETWORKS + b"# tampered\n"))

    def test_default_networks_same_bytes_replacement_refused(self):
        self.provision()
        def replace(s, vm):
            path = self.root / "lima" / "_config" / "networks.yaml"
            path.rename(self.root / "old-networks.yaml")
            path.write_bytes(DEFAULT_NETWORKS)
        self.assert_guarded(replace)

    def test_arbitrary_networks_at_first_start_refused(self):
        def inject(operation, root, vm):
            if operation == "start":
                (root / "lima" / "_config" / "networks.yaml").write_text("networks: {}\n")
        self.fake.before = inject
        with self.assertRaisesRegex(ref.Refusal, "unexpected Lima default networks"):
            self.provision()
        self.assertEqual(self.receipt()["phase"], "starting")

    def crash(self):
        status = self.provision("--timeout", "10")
        with self.open() as run:
            run.destructive("crash", status["run_id"])
        return status

    def test_restart_exact_stopped_instance_and_same_daemon_durable_intent(self):
        status = self.crash()
        old = self.receipt()
        self.assertTrue(old["crash_verified"])
        self.assertEqual(old["lifecycle"][-1]["status"], "Stopped")
        def inspect(operation, root, vm):
            if operation == "start":
                durable = self.receipt()
                self.assertEqual(durable["phase"], "restarting")
                self.assertEqual(durable["lifecycle"][-1]["daemon_id"], old["daemon_id"])
                self.assertEqual(durable["restart_count"], 1)
                self.assertFalse(durable["crash_verified"])
        self.fake.before = inspect
        with self.open() as run:
            self.assertEqual(run.restart(status["run_id"])["phase"], "ready")
        new = self.receipt()
        self.assertEqual(old["daemon_id"], new["daemon_id"])
        self.assertEqual(old["globals"], new["globals"])
        socket_key = f'lima/{status["name"]}/sock/docker.sock'
        self.assertNotEqual(old["records"][socket_key]["ino"], new["records"][socket_key]["ino"])
        for path, record in old["records"].items():
            if path != socket_key:
                self.assertEqual(record, new["records"][path])
        self.assertEqual([event["phase"] for event in new["lifecycle"]],
                         ["crashing", "crashed", "restarting", "restart-unverified", "ready"])
        self.assertTrue(all(0 < kw["timeout"] <= 10 for _, kw in self.fake.calls))
        with self.open() as run:
            self.assertEqual(run.destructive("destroy", status["run_id"])["phase"], "destroyed")

    def test_crash_must_observe_stopped_not_just_stop_success(self):
        status = self.provision()
        self.fake.stop_keeps_running = True
        with self.open() as run:
            with self.assertRaisesRegex(ref.Refusal, "unexpected instance status"):
                run.destructive("crash", status["run_id"])
        self.assertEqual(self.receipt()["phase"], "crashing")
        self.assertFalse(self.receipt()["crash_verified"])
        count = len(self.fake.calls)
        with self.open() as run:
            with self.assertRaisesRegex(ref.Refusal, "durably verified crash"):
                run.restart(status["run_id"])
        self.assertEqual(len(self.fake.calls), count)

    def test_crash_timeout_is_not_restartable_but_safe_stopped_destroy_works(self):
        status = self.provision()
        self.fake.fail = "stop"
        with self.open() as run:
            with self.assertRaises(subprocess.TimeoutExpired):
                run.destructive("crash", status["run_id"])
        with self.open() as run:
            with self.assertRaisesRegex(ref.Refusal, "durably verified crash"):
                run.restart(status["run_id"])
            self.assertEqual(run.status()["instance_status"], "Stopped")
            self.assertEqual(run.destructive("destroy", status["run_id"])["phase"], "destroyed")

    def test_stopped_stale_recorded_socket_status_restart_and_destroy(self):
        self.fake.retain_socket = True
        status = self.crash()
        self.fake.fail = "--config"
        with self.open() as run:
            self.assertEqual(run.status()["instance_status"], "Stopped")
        self.fake.fail = None
        with self.open() as run:
            self.assertEqual(run.restart(status["run_id"])["phase"], "ready")
            run.destructive("crash", status["run_id"])
        self.fake.fail = "--config"
        with self.open() as run:
            self.assertEqual(run.destructive("destroy", status["run_id"])["phase"], "destroyed")

    def test_restart_requires_recorded_crash_and_correct_run_id(self):
        status = self.provision()
        with self.open() as run:
            count = len(self.fake.calls)
            with self.assertRaisesRegex(ref.Refusal, "durably verified crash"):
                run.restart(status["run_id"])
            with self.assertRaisesRegex(ref.Refusal, "run-id"):
                run.restart("not-our-run")
            self.assertEqual(len(self.fake.calls), count)
            run.destructive("crash", status["run_id"])
        state = self.receipt()
        state.pop("crash_verified")  # Legacy/unverified 'crashed' receipt is not sufficient.
        ref.save(self.root, state)
        with self.open() as run:
            with self.assertRaisesRegex(ref.Refusal, "durably verified crash"):
                run.restart(status["run_id"])

    def test_restart_list_identity_and_shape_fail_closed(self):
        status = self.crash()
        row = {"name": status["name"], "dir": str(self.root / "lima" / status["name"]),
               "vmType": "vz", "arch": "aarch64", "status": "Stopped"}
        invalid = ["", "[]", "null", "{", json.dumps(row) + "\n" + json.dumps(row)]
        invalid += [json.dumps({**row, key: value}) for key, value in (
            ("name", "foreign"), ("dir", "/foreign"), ("vmType", "qemu"),
            ("arch", "x86_64"), ("status", "Running"), ("status", "Broken"), ("status", []), ("status", {}))]
        count = sum(argv[1] == "start" for argv, _ in self.fake.calls)
        for output in invalid:
            with self.subTest(output=output):
                self.fake.list_output = output
                with self.open() as run:
                    with self.assertRaises((ref.Refusal, ValueError)):
                        run.restart(status["run_id"])
        self.assertEqual(sum(argv[1] == "start" for argv, _ in self.fake.calls), count)

    def test_restart_unrecorded_socket_before_start_refused(self):
        status = self.crash()
        path = self.root / "lima" / status["name"] / "sock" / "docker.sock"
        connection = socket.socket(socket.AF_UNIX)
        self.fake.sockets.append(connection)
        connection.bind(str(path))
        count = len(self.fake.calls)
        with self.assertRaisesRegex(ref.Refusal, "identity changed"):
            with self.open() as run:
                run.restart(status["run_id"])
        self.assertEqual(len(self.fake.calls), count)

    def test_restart_timeout_never_adopts_new_socket_or_retries(self):
        status = self.crash()
        old = self.receipt()["records"]
        self.fake.fail = "start"
        with self.open() as run:
            with self.assertRaises(subprocess.TimeoutExpired):
                run.restart(status["run_id"])
        self.assertEqual(self.receipt()["phase"], "restart-failed")
        self.assertEqual(self.receipt()["records"], old)
        count = len(self.fake.calls)
        with self.assertRaises(ref.Refusal):
            with self.open() as run:
                run.restart(status["run_id"])
        self.assertEqual(len(self.fake.calls), count)

    def test_restart_failure_without_start_side_effects_allows_safe_destroy_not_retry(self):
        status = self.crash()
        def fail(operation, root, vm):
            if operation == "start":
                raise subprocess.TimeoutExpired(["fake-start"], 10)
        self.fake.before = fail
        with self.open() as run:
            with self.assertRaises(subprocess.TimeoutExpired):
                run.restart(status["run_id"])
        with self.open() as run:
            self.assertEqual(run.status()["instance_status"], "Stopped")
            with self.assertRaisesRegex(ref.Refusal, "durably verified crash"):
                run.restart(status["run_id"])
            self.assertEqual(run.destructive("destroy", status["run_id"])["phase"], "destroyed")

    def test_restart_foreign_daemon_is_terminal_and_blocks_delete(self):
        status = self.crash()
        old_id = status["daemon_id"]
        self.fake.daemon_id = "foreign-restarted-daemon"
        with self.open() as run:
            with self.assertRaisesRegex(ref.Refusal, "daemon identity changed"):
                run.restart(status["run_id"])
        self.assertEqual(self.receipt()["phase"], "restart-failed")
        self.assertEqual(self.receipt()["daemon_id"], old_id)
        with self.open() as run:
            with self.assertRaisesRegex(ref.Refusal, "durably verified crash"):
                run.restart(status["run_id"])
            with self.assertRaisesRegex(ref.Refusal, "daemon identity changed"):
                run.destructive("destroy", status["run_id"])
        self.assertFalse(any(argv[1] == "delete" for argv, _ in self.fake.calls))

    def test_restart_immutable_tamper_before_and_during_start_refused(self):
        for index, target in enumerate(("image", "config", "tool", "root", "socket-parent", "networks")):
            with self.subTest(target=target):
                self.root = self.base / f"r{index}"
                status = self.crash()
                def replace(operation, root, vm):
                    if operation != "start":
                        return
                    path = {"image": self.image, "config": vm / "lima.yaml", "tool": self.base / "docker",
                            "root": root, "socket-parent": vm / "sock",
                            "networks": root / "lima" / "_config" / "networks.yaml"}[target]
                    if path.is_dir():
                        path.chmod(0o710)
                    else:
                        path.write_bytes(path.read_bytes() + b"tamper")
                self.fake.before = replace
                with self.open() as run:
                    with self.assertRaises(ref.Refusal):
                        run.restart(status["run_id"])
                self.assertNotEqual(self.receipt()["phase"], "ready")
                self.fake.before = None
                if target == "image":
                    self.image.write_bytes(b"pinned preinstalled cloud image fixture")
                if target == "tool":
                    (self.base / "docker").write_text("#!/bin/sh\nexit 97\n")

    def test_restart_image_tamper_before_start_refused(self):
        status = self.crash()
        self.image.write_bytes(b"foreign image")
        count = len(self.fake.calls)
        with self.open() as run:
            with self.assertRaisesRegex(ref.Refusal, "identity changed"):
                run.restart(status["run_id"])
        self.assertEqual(len(self.fake.calls), count)

    def test_restart_attempt_and_receipt_bounds(self):
        status = self.crash()
        state = self.receipt()
        for value in (True, -1, ref.MAX_RESTARTS + 1):
            ref.save(self.root, {**state, "restart_count": value})
            with self.assertRaisesRegex(ref.Refusal, "restart count bound"):
                with self.open():
                    pass
        ref.save(self.root, {**state, "restart_count": ref.MAX_RESTARTS})
        count = len(self.fake.calls)
        with self.open() as run:
            with self.assertRaisesRegex(ref.Refusal, "attempt limit"):
                run.restart(status["run_id"])
            self.assertEqual(len(self.fake.calls), count)
            self.assertEqual(run.destructive("destroy", status["run_id"])["phase"], "destroyed")

    def test_crash_foreign_post_stop_list_does_not_commit_crashed(self):
        status = self.provision()
        def replace(operation, root, vm):
            if operation == "list" and self.receipt()["phase"] == "crashing":
                self.fake.list_output = json.dumps({"name": status["name"], "dir": "/foreign",
                    "vmType": "vz", "arch": "aarch64", "status": "Stopped"})
        self.fake.before = replace
        with self.open() as run:
            with self.assertRaisesRegex(ref.Refusal, "foreign instance"):
                run.destructive("crash", status["run_id"])
        self.assertEqual(self.receipt()["phase"], "crashing")
        self.assertFalse(self.receipt()["crash_verified"])
        self.assertEqual(self.receipt()["lifecycle"][-1]["phase"], "crashing")

    def test_restart_nonzero_start_and_invalid_candidate_socket_are_terminal(self):
        original = self.fake
        for index, failure in enumerate(("exit", "missing", "regular", "permissions")):
            with self.subTest(failure=failure):
                self.root = self.base / f"f{index}"
                status = self.crash()
                old = self.receipt()["records"]
                def fake(argv, **kwargs):
                    result = original(argv, **kwargs)
                    if argv[1] == "start":
                        path = self.root / "lima" / status["name"] / "sock" / "docker.sock"
                        if failure == "exit":
                            return SimpleNamespace(returncode=1)
                        if failure in ("missing", "regular"):
                            path.unlink()
                            if failure == "regular":
                                path.write_bytes(b"not a socket")
                        else:
                            path.chmod(stat.S_IMODE(path.stat().st_mode) ^ 0o100)
                    return result
                with ref.Reference(self.root, fake) as run:
                    with self.assertRaises((ref.Refusal, OSError)):
                        run.restart(status["run_id"])
                self.assertEqual(self.receipt()["phase"], "restart-failed")
                self.assertEqual(self.receipt()["records"], old)

    def test_restart_post_start_identity_change_is_terminal(self):
        status = self.crash()
        def replace(operation, root, vm):
            if operation == "start":
                self.fake.list_output = json.dumps({"name": status["name"], "dir": str(vm),
                    "vmType": "qemu", "arch": "aarch64", "status": "Running"})
        self.fake.before = replace
        with self.open() as run:
            with self.assertRaisesRegex(ref.Refusal, "foreign instance"):
                run.restart(status["run_id"])
        self.assertEqual(self.receipt()["phase"], "restart-failed")
        self.assertEqual(self.receipt()["daemon_id"], status["daemon_id"])

    def test_restart_intent_fsync_failure_prevents_start(self):
        status = self.crash()
        count = sum(argv[1] == "start" for argv, _ in self.fake.calls)
        original = ref.sync_directory
        def fail(path):
            if path == self.root and self.receipt()["phase"] == "restarting":
                raise OSError("simulated fsync failure")
            return original(path)
        with self.open() as run, patch.object(ref, "sync_directory", side_effect=fail):
            with self.assertRaisesRegex(OSError, "fsync failure"):
                run.restart(status["run_id"])
        self.assertEqual(sum(argv[1] == "start" for argv, _ in self.fake.calls), count)
        with self.open() as run:
            with self.assertRaisesRegex(ref.Refusal, "durably verified crash"):
                run.restart(status["run_id"])

    def test_interrupted_restart_phases_allow_only_verified_status_and_destroy(self):
        for index, phase in enumerate(("restarting", "restart-unverified")):
            self.root = self.base / f"i{index}"
            status = self.crash()
            if phase == "restart-unverified":
                with self.open() as run:
                    run.restart(status["run_id"])
            # Model process death after a durable intent or candidate-socket receipt.
            state = self.receipt()
            ref.save(self.root, {**state, "phase": phase, "crash_verified": False})
            with self.open() as run:
                count = len(self.fake.calls)
                with self.assertRaisesRegex(ref.Refusal, "durably verified crash"):
                    run.restart(status["run_id"])
                self.assertEqual(len(self.fake.calls), count)
                expected = "Running" if phase == "restart-unverified" else "Stopped"
                self.assertEqual(run.status()["instance_status"], expected)
                self.assertEqual(run.destructive("destroy", status["run_id"])["phase"], "destroyed")

    def test_nondictionary_receipt_is_cleanly_refused(self):
        self.provision()
        count = len(self.fake.calls)
        for value in ([], None, 1, "foreign"):
            (self.root / "state.json").write_text(json.dumps(value))
            with self.assertRaisesRegex(ref.Refusal, "ownership object"):
                with self.open():
                    pass
        self.assertEqual(len(self.fake.calls), count)

    def test_restart_list_output_bound_and_timeout(self):
        status = self.crash()
        for oversized in (False, True):
            self.fake.fail = None if oversized else "list"
            self.fake.list_output = "x" * (ref.MAX_OUTPUT + 1) if oversized else None
            with self.open() as run:
                with self.assertRaises(ref.Refusal if oversized else subprocess.TimeoutExpired):
                    run.restart(status["run_id"])
        self.assertEqual(self.receipt()["phase"], "crashed")

    def test_flag_bounds_before_side_effects(self):
        for key, (low, high) in ref.LIMITS.items():
            for invalid in (low - 1, high + 1):
                with self.subTest(key=key, invalid=invalid):
                    args = self.args("--" + key.replace("_", "-"), str(invalid))
                    with self.assertRaises(ref.Refusal):
                        ref.provision(args, self.fake)
                    self.assertFalse(self.root.exists())
        self.assertEqual(self.fake.calls, [])

    def test_pinned_inputs_and_opt_in_required(self):
        for key, value in (("image_sha256", "0" * 64), ("image_sha256", "latest"),
                           ("engine_version", "latest"), ("engine_version", ">=28"),
                           ("allow_disposable_vm", False), ("image", "https://example.invalid/image")):
            with self.subTest(key=key, value=value):
                args = self.args()
                setattr(args, key, value)
                with self.assertRaises(ref.Refusal):
                    ref.provision(args, self.fake)
                self.assertFalse(self.root.exists())
        self.assertEqual(self.fake.calls, [])

    def test_root_must_be_fresh_and_not_ambient_home(self):
        self.root.mkdir()
        with self.assertRaises(ref.Refusal):
            self.provision()
        self.root.rmdir()
        for key in ("LIMA_HOME", "COLIMA_HOME"):
            with self.assertRaises(ref.Refusal):
                self.provision("--root", os.environ[key])
        self.assertEqual(self.fake.calls, [])

    def test_symlink_image_and_root_refused(self):
        link = self.base / "link"
        link.symlink_to(self.image)
        with self.assertRaises(ref.Refusal):
            self.provision("--image", str(link))
        self.root.symlink_to(self.base / "missing")
        with self.assertRaises(ref.Refusal):
            self.provision()
        self.assertEqual(self.fake.calls, [])

    def test_writable_image_and_executables_refused_before_side_effects(self):
        for path in (self.image, self.base / "limactl", self.base / "docker"):
            original = stat.S_IMODE(path.stat().st_mode)
            for bit in (0o020, 0o002):
                with self.subTest(path=path.name, bit=bit):
                    path.chmod(original | bit)
                    try:
                        with self.assertRaisesRegex(ref.Refusal, "group/other-writable"):
                            self.provision()
                        self.assertFalse(self.root.exists())
                        self.assertEqual(self.fake.calls, [])
                    finally:
                        path.chmod(original)

    def test_untrusted_input_and_parent_owners_refused(self):
        # No chown/elevation: simulate ownership metadata, not execution.
        original_stat, original_fstat = os.stat, os.fstat
        for path in (self.image, self.base / "limactl", self.base / "docker", self.base):
            target = path.stat()
            def foreign(info):
                if (info.st_dev, info.st_ino) == (target.st_dev, target.st_ino):
                    values = list(info)
                    values[4] = max(os.getuid(), 0) + 10000
                    return os.stat_result(values)
                return info
            with self.subTest(path=path.name), \
                    patch.object(ref.os, "stat", side_effect=lambda *a, **kw: foreign(original_stat(*a, **kw))), \
                    patch.object(ref.os, "fstat", side_effect=lambda *a: foreign(original_fstat(*a))):
                with self.assertRaisesRegex(ref.Refusal, "untrusted owner"):
                    self.provision()
                self.assertFalse(self.root.exists())
                self.assertEqual(self.fake.calls, [])

    def test_mutable_parent_components_refused(self):
        for mode in (0o720, 0o702, 0o1777):
            with self.subTest(mode=oct(mode)):
                self.base.chmod(mode)
                try:
                    with self.assertRaisesRegex(ref.Refusal, "group/other-writable"):
                        self.provision()
                    self.assertFalse(self.root.exists())
                    self.assertEqual(self.fake.calls, [])
                finally:
                    self.base.chmod(0o700)
        # A separate executable/image ancestor must also be checked, not just
        # the run root's common parent.
        parent = self.base / "inputs"
        parent.mkdir(mode=0o700)
        for name in ("image.raw", "limactl", "docker"):
            source = self.image if name == "image.raw" else self.base / name
            shutil.copy2(source, parent / name)
        parent.chmod(0o777)
        try:
            for flag, name in (("image", "image.raw"), ("limactl", "limactl"), ("docker", "docker")):
                with self.subTest(flag=flag), self.assertRaisesRegex(ref.Refusal, "group/other-writable"):
                    self.provision("--" + flag, str(parent / name))
            self.assertEqual(self.fake.calls, [])
            self.assertFalse(self.root.exists())
        finally:
            parent.chmod(0o700)

    def test_mutable_fixture_source_refused(self):
        ref.FIXTURE_SOURCE.chmod(0o666)
        with self.assertRaisesRegex(ref.Refusal, "group/other-writable"):
            self.provision("--owned-fixture")
        self.assertFalse(self.root.exists())
        self.assertEqual(self.fake.calls, [])

    def test_system_sticky_temp_policy(self):
        system_tmp = Path("/private/tmp" if sys.platform == "darwin" else "/tmp")
        metadata = lambda uid, mode: SimpleNamespace(st_uid=uid, st_mode=stat.S_IFDIR | mode)
        ref.trusted_info(system_tmp, metadata(0, 0o1777))
        for path, uid, mode in ((system_tmp, 0, 0o777),
                                (system_tmp, os.getuid() + 10000, 0o1777),
                                (self.base, 0, 0o1777),
                                (self.base, os.getuid(), 0o1777)):
            with self.subTest(path=path, uid=uid, mode=mode), self.assertRaises(ref.Refusal):
                ref.trusted_info(path, metadata(uid, mode))
        # This suite's real private child under canonical system tmp is accepted.
        self.assertEqual(ref.identity(self.base)["uid"], os.getuid())
        if sys.platform == "darwin":
            with self.assertRaisesRegex(ref.Refusal, "noncanonical"):
                ref.identity(Path("/tmp") / self.base.name)

    def test_permissions_rechecked_before_any_lifecycle_command(self):
        self.provision()
        for path in (self.base / "limactl", self.base / "docker", self.base):
            original = stat.S_IMODE(path.stat().st_mode)
            count = len(self.fake.calls)
            path.chmod(original | 0o020)
            try:
                with self.assertRaisesRegex(ref.Refusal, "group/other-writable"):
                    with self.open():
                        pass
                self.assertEqual(len(self.fake.calls), count)
            finally:
                path.chmod(original)

    def test_hash_uses_inspected_fd_and_detects_replacement(self):
        original_digest = ref.hashlib.file_digest
        def replace(stream, algorithm):
            self.assertEqual(os.fstat(stream.fileno()).st_ino, self.image.stat().st_ino)
            self.image.rename(self.base / "old-image.raw")
            self.image.write_bytes(b"pinned preinstalled cloud image fixture")
            return original_digest(stream, algorithm)
        with patch.object(ref.hashlib, "file_digest", side_effect=replace):
            with self.assertRaisesRegex(ref.Refusal, "file (changed|replaced) while hashing"):
                ref.identity(self.image, hashed=True)

    def test_hash_detects_in_place_mutation(self):
        original_digest = ref.hashlib.file_digest
        def mutate(stream, algorithm):
            result = original_digest(stream, algorithm)
            self.image.write_bytes(b"changed after hashing")
            return result
        with patch.object(ref.hashlib, "file_digest", side_effect=mutate):
            with self.assertRaisesRegex(ref.Refusal, "file changed while hashing"):
                ref.identity(self.image, hashed=True)

    def test_nofollow_open_refuses_raced_image_symlink(self):
        original_open = os.open
        def replace(path, flags, *args, **kwargs):
            if path == self.image.name and kwargs.get("dir_fd") is not None:
                self.image.rename(self.base / "old-image.raw")
                self.image.symlink_to(self.base / "old-image.raw")
            return original_open(path, flags, *args, **kwargs)
        with patch.object(ref.os, "open", side_effect=replace), self.assertRaises(OSError):
            ref.identity(self.image, hashed=True)

    def test_nofollow_walk_refuses_raced_parent_symlink(self):
        original_open = os.open
        moved = self.base.with_name(self.base.name + "-moved")
        def replace(path, flags, *args, **kwargs):
            if path == self.base.name and kwargs.get("dir_fd") is not None:
                self.base.rename(moved)
                self.base.symlink_to(moved, target_is_directory=True)
            return original_open(path, flags, *args, **kwargs)
        try:
            with patch.object(ref.os, "open", side_effect=replace), self.assertRaises(OSError):
                ref.identity(self.image, hashed=True)
        finally:
            if moved.exists():
                self.base.unlink()
                moved.rename(self.base)

    def test_foreign_config_content_and_inode(self):
        self.provision()
        def change(s, vm):
            (vm / "lima.yaml").write_text("mounts: [{location: '~'}]\n")
        self.assert_guarded(change)

    def test_same_bytes_config_replacement_refused(self):
        self.provision()
        def change(s, vm):
            path = vm / "lima.yaml"
            contents = path.read_bytes()
            path.rename(vm / "original.yaml")
            path.write_bytes(contents)
        self.assert_guarded(change)

    def test_vm_directory_replacement_refused(self):
        self.provision()
        def change(s, vm):
            vm.rename(vm.with_name("old-vm"))
            vm.mkdir()
        self.assert_guarded(change)

    def test_global_config_injection_refused(self):
        self.provision()
        self.assert_guarded(lambda s, vm: (self.root / "lima" / "_config" / "override.yaml").write_text("mounts: []\n"))

    def test_foreign_home_symlink_refused(self):
        self.provision()
        def change(s, vm):
            home = self.root / "lima"
            home.rename(self.root / "original-home")
            home.symlink_to(self.root / "original-home")
        self.assert_guarded(change)

    def test_foreign_endpoint_and_regular_file_refused(self):
        self.provision()
        def change(s, vm):
            endpoint = vm / "sock" / "docker.sock"
            endpoint.unlink()
            endpoint.write_bytes(b"not a socket")
        self.assert_guarded(change)

    def test_socket_symlink_refused(self):
        self.provision()
        def change(s, vm):
            endpoint = vm / "sock" / "docker.sock"
            endpoint.rename(vm / "sock" / "original.sock")
            endpoint.symlink_to(vm / "sock" / "original.sock")
        self.assert_guarded(change)

    def test_foreign_receipt_root_and_endpoint(self):
        self.provision()
        state = self.receipt()
        for key in ("root", "endpoint", "name"):
            modified = {**state, key: "/foreign"}
            ref.save(self.root, modified) if key != "root" else (self.root / "state.json").write_text(json.dumps(modified))
            count = len(self.fake.calls)
            with self.assertRaises(ref.Refusal):
                with self.open():
                    pass
            self.assertEqual(len(self.fake.calls), count)
        ref.save(self.root, state)

    def test_tool_replacement_and_run_id_guard(self):
        status = self.provision()
        count = len(self.fake.calls)
        with self.open() as run:
            with self.assertRaises(ref.Refusal):
                run.destructive("destroy", "not-our-run")
        self.assertEqual(len(self.fake.calls), count)
        self.assert_guarded(lambda s, vm: (self.base / "limactl").write_text("foreign tool"))
        self.assertEqual(status["phase"], "ready")

    def test_foreign_daemon_identity_blocks_delete(self):
        state = self.provision()
        self.fake.daemon_id = "someone-elses-daemon"
        with self.open() as run:
            with self.assertRaisesRegex(ref.Refusal, "daemon identity changed"):
                run.destructive("destroy", state["run_id"])
        self.assertFalse(any(argv[1] == "delete" for argv, _ in self.fake.calls))

    def test_interrupted_create_is_never_adopted_or_cleaned(self):
        self.fake.fail = "create"
        with self.assertRaises(subprocess.TimeoutExpired):
            self.provision()
        state = self.receipt()
        self.assertEqual(state["phase"], "creating")
        self.assertIsNone(state["daemon_id"])
        self.assertTrue((self.root / "lima" / state["name"]).is_dir())
        count = len(self.fake.calls)
        with self.assertRaises(ref.Refusal):
            with self.open() as run:
                run.destructive("destroy", state["run_id"])
        self.assertEqual(len(self.fake.calls), count)
        self.assertTrue(list((self.root / "artifacts").glob("create-*")))

    def test_interrupted_start_preserves_config_and_refuses_adoption(self):
        self.fake.fail = "start"
        with self.assertRaises(subprocess.TimeoutExpired):
            self.provision()
        state = self.receipt()
        self.assertEqual(state["phase"], "starting")
        self.assertIn(f'lima/{state["name"]}/lima.yaml', state["records"])
        count = len(self.fake.calls)
        with self.assertRaises(ref.Refusal):
            with self.open() as run:
                run.destructive("destroy", state["run_id"])
        self.assertEqual(len(self.fake.calls), count)

    def test_wrong_engine_version_preserves_unverified_vm(self):
        self.fake.engine_version = "99.0.0"
        with self.assertRaisesRegex(ref.Refusal, "foreign engine version"):
            self.provision()
        self.assertEqual(self.receipt()["phase"], "started-unverified")
        with self.open() as run:
            with self.assertRaises(ref.Refusal):
                run.destructive("destroy", self.receipt()["run_id"])
        self.assertFalse(any(argv[1] in ("stop", "delete") for argv, _ in self.fake.calls))

    def test_lima_version_is_pinned_before_create(self):
        self.fake.lima_version = "999.0.0"
        with self.assertRaisesRegex(ref.Refusal, "requires exactly Lima"):
            self.provision()
        self.assertEqual([argv[1] for argv, _ in self.fake.calls], ["--version"])
        self.assertEqual(self.receipt()["phase"], "prepared")

    def test_config_rechecked_after_daemon_probe_before_delete(self):
        status = self.provision()
        def replace(operation, root, vm):
            if operation == "--config":
                (vm / "lima.yaml").write_text("foreign config")
        self.fake.before = replace
        with self.open() as run:
            with self.assertRaises(ref.Refusal):
                run.destructive("destroy", status["run_id"])
        self.assertFalse(any(argv[1] == "delete" for argv, _ in self.fake.calls))

    def test_receipt_replacement_while_open_refused(self):
        state = self.provision()
        with self.open() as run:
            path = self.root / "state.json"
            contents = path.read_bytes()
            path.rename(self.root / "old-state.json")
            ref.write_new(path, contents)
            count = len(self.fake.calls)
            with self.assertRaisesRegex(ref.Refusal, "identity changed"):
                run.destructive("destroy", state["run_id"])
            self.assertEqual(len(self.fake.calls), count)
            self.assertEqual(path.read_bytes(), contents)

    def test_ready_socket_displacement_refused(self):
        self.provision()
        self.assert_guarded(lambda s, vm: (vm / "sock" / "docker.sock").rename(vm / "sock" / "moved.sock"))

    def test_image_replaced_during_create_refused_before_start(self):
        def replace(operation, root, vm):
            if operation == "create":
                contents = self.image.read_bytes()
                self.image.rename(self.base / "old-image.raw")
                self.image.write_bytes(contents)
        self.fake.before = replace
        with self.assertRaisesRegex(ref.Refusal, "identity changed"):
            self.provision()
        self.assertEqual(self.receipt()["phase"], "creating")
        self.assertFalse(any(argv[1] == "start" for argv, _ in self.fake.calls))

    def test_image_replaced_during_start_refused(self):
        def replace(operation, root, vm):
            if operation == "start":
                contents = self.image.read_bytes()
                self.image.rename(self.base / "old-image.raw")
                self.image.write_bytes(contents)
        self.fake.before = replace
        with self.assertRaisesRegex(ref.Refusal, "identity changed"):
            self.provision()
        self.assertEqual(self.receipt()["phase"], "starting")
        self.assertFalse(any(argv[1] in ("stop", "delete") for argv, _ in self.fake.calls))

    def test_default_home_alias_refused(self):
        home = self.base / "home"
        home.mkdir()
        (home / ".lima").mkdir()
        alias = self.base / "home-alias"
        alias.symlink_to(home)
        with patch.object(ref.Path, "home", return_value=alias):
            with self.assertRaisesRegex(ref.Refusal, "ambient"):
                self.provision("--root", str(home / ".lima" / "run"))
        self.assertEqual(self.fake.calls, [])

    def test_disk_space_and_long_socket_path_preflight(self):
        with patch.object(ref.os, "statvfs", return_value=SimpleNamespace(f_bavail=0, f_frsize=1)):
            with self.assertRaisesRegex(ref.Refusal, "free space"):
                self.provision()
        with self.assertRaisesRegex(ref.Refusal, "too long"):
            self.provision("--root", str(self.base / ("x" * 110)))
        self.assertFalse(self.root.exists())
        self.assertEqual(self.fake.calls, [])

    def test_hardlinked_input_refused(self):
        os.link(self.image, self.base / "hardlink.raw")
        with self.assertRaisesRegex(ref.Refusal, "hardlinked"):
            self.provision()
        self.assertEqual(self.fake.calls, [])

    def test_root_inode_replacement_refused(self):
        self.provision()
        def replace(s, vm):
            self.root.rename(self.base / "old-root")
            self.root.mkdir(mode=0o700)
            shutil.copyfile(self.base / "old-root" / "lock", self.root / "lock")
            ref.write_new(self.root / "state.json", (self.base / "old-root" / "state.json").read_bytes())
        self.assert_guarded(replace)

    def test_record_bounds_tampering_refused(self):
        self.provision()
        state = self.receipt()
        ref.save(self.root, {**state, "cpus": True})
        count = len(self.fake.calls)
        with self.assertRaisesRegex(ref.Refusal, "bound"):
            with self.open():
                pass
        self.assertEqual(len(self.fake.calls), count)

    def test_lima_keys_created_only_on_start_are_pinned(self):
        original = self.fake
        def fake(argv, **kwargs):
            config = self.root / "lima" / "_config"
            if argv[1] == "start":
                config.mkdir(mode=0o700)
                (config / "user").write_text("private-key")
                (config / "user.pub").write_text("public-key")
            result = original(argv, **kwargs)
            if argv[1] == "create":
                shutil.rmtree(config)
            return result
        self.assertEqual(ref.provision(self.args(), fake)["phase"], "ready")
        self.assertIn("lima/_config/user", self.receipt()["globals"])

    def test_non_socket_endpoint_rejected_at_establishment(self):
        original = self.fake
        def fake(argv, **kwargs):
            result = original(argv, **kwargs)
            if argv[1] == "start":
                state = self.receipt()
                endpoint = self.root / "lima" / state["name"] / "sock" / "docker.sock"
                endpoint.unlink()
                endpoint.write_bytes(b"foreign")
            return result
        with self.assertRaisesRegex(ref.Refusal, "not a Unix socket"):
            ref.provision(self.args(), fake)
        self.assertEqual(self.receipt()["phase"], "started-unverified")

    def test_unexpected_successful_delete_leftovers_refused(self):
        state = self.provision()
        original = self.fake
        def fake(argv, **kwargs):
            if argv[1] == "delete":
                return SimpleNamespace(returncode=0)
            return original(argv, **kwargs)
        with ref.Reference(self.root, fake) as run:
            with self.assertRaisesRegex(ref.Refusal, "left VM records"):
                run.destructive("destroy", state["run_id"])
        self.assertEqual(self.receipt()["phase"], "destroying")
        self.assertTrue((self.root / "artifacts").is_dir())

    def test_bounded_runner_caps_both_streams_and_timeout(self):
        # These are tiny Python children, never Lima/Docker, network, or VMs.
        def execute(script, timeout: float = 2):
            with (self.base / "out").open("wb") as out, (self.base / "err").open("wb") as err:
                return ref.run_bounded([sys.executable, "-c", script], env={}, cwd=self.base,
                    stdin=subprocess.DEVNULL, stdout=out, stderr=err, timeout=timeout, check=False)
        with patch.object(ref, "MAX_OUTPUT", 1024):
            for fd in (1, 2):
                with self.assertRaisesRegex(ref.Refusal, "output limit"):
                    execute(f"import os; os.write({fd}, b'x' * 4096)")
                self.assertLessEqual((self.base / "out").stat().st_size, 1024)
                self.assertLessEqual((self.base / "err").stat().st_size, 1024)
        with self.assertRaises(subprocess.TimeoutExpired):
            execute("import time; time.sleep(10)", timeout=0.05)
        self.assertEqual(execute("print('bounded')").returncode, 0)
        self.assertEqual((self.base / "out").read_text(), "bounded\n")

    def test_cleanup_wait_timeout_preserves_primary_and_closes_pipes(self):
        class Child:
            def __init__(self):
                self.stdout = io.BytesIO()
                self.stderr = io.BytesIO()
                self.killed = False
            def poll(self):
                return None
            def kill(self):
                self.killed = True
            def wait(self, **kwargs):
                raise subprocess.TimeoutExpired(["fake-child"], kwargs["timeout"])
        for primary in (ref.Refusal("output limit"), subprocess.TimeoutExpired(["primary"], 0.1)):
            child = Child()
            with self.subTest(primary=type(primary).__name__), \
                    patch.object(ref.subprocess, "Popen", return_value=child), \
                    patch.object(ref.selectors, "DefaultSelector", side_effect=primary):
                with self.assertRaises(type(primary)) as raised:
                    ref.run_bounded(["fake-child"], env={}, cwd=self.base, stdin=subprocess.DEVNULL,
                                    stdout=io.BytesIO(), stderr=io.BytesIO(), timeout=1, check=False)
                self.assertIs(raised.exception, primary)
                self.assertIn("unreaped", primary.__notes__[0])
                self.assertTrue(child.killed)
                self.assertTrue(child.stdout.closed)
                self.assertTrue(child.stderr.closed)

    def test_no_default_context_cli_and_help_engine_free(self):
        with self.assertRaises(SystemExit) as result:
            ref.parser().parse_args(["destroy", "--root", str(self.root)])
        self.assertEqual(result.exception.code, 2)
        self.assertEqual(self.fake.calls, [])


if __name__ == "__main__":
    unittest.main()
